# Там где АПИ пока под вопросом, то ли это температура с датчика или еще доп апи по температуре погоды например

@startuml
title SmartHome Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "User", "A user of the smart home system")
System(SmartHome, "FitLife System", "System supports heating control in the house")
System_Ext(api, "Third-Party API", "External API for temperature data integration")
System_Ext(sensors, "Sensor System", "")

Rel(user, SmartHome, "Uses the system")
Rel(SmartHome, api, "Fetches fitness data")
Rel(SmartHome, sensors, "Controls the sensor")

@enduml